services:
  app:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bdd_sae_rift
      - SPRING_DATASOURCE_USERNAME=spring
      - SPRING_DATASOURCE_PASSWORD=springRift123456

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: springRift123456
      POSTGRES_DB: bdd_sae_rift
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
